#!/bin/bash

echo "================================"
echo "📊 SyncNote Backend Architecture"
echo "================================"
echo ""
echo "🚀 ENTRY POINT: server.js"
echo "   └─ Contains: app.listen(PORT)"
echo ""
echo "📦 APP SETUP: src/app.js"
echo "   ├─ Creates Express app"
echo "   ├─ Applies middleware"
echo "   └─ Mounts routes"
echo ""
echo "🛣️  ROUTES: src/routes/index.js"
echo "   ├─ GET / (welcome)"
echo "   ├─ GET /health (status)"
echo "   └─ (Add more routes here)"
echo ""
echo "⚙️  MIDDLEWARE:"
echo "   ├─ src/middleware/corsMiddleware.js"
echo "   └─ src/middleware/errorHandler.js"
echo ""
echo "🔧 CONFIG: src/config/environment.js"
echo "   └─ Loads variables from .env"
echo ""
echo "📝 LOGGING: src/utils/logger.js"
echo "   └─ Structured logging"
echo ""
echo "================================"
echo "🌍 AVAILABLE ENDPOINTS"
echo "================================"
echo ""
echo "Root Level:"
echo "  GET http://localhost:5000/"
echo "    → Welcome page"
echo ""
echo "API Level:"
echo "  GET http://localhost:5000/api/v1"
echo "    → API welcome"
echo ""
echo "Health:"
echo "  GET http://localhost:5000/api/v1/health"
echo "    → Server status"
echo ""
echo "================================"
echo "📋 REQUEST FLOW"
echo "================================"
echo ""
echo "Request → server.js (app.listen)"
echo "   ↓"
echo "src/app.js (middleware chain)"
echo "   ↓"
echo "src/routes/index.js (route handler)"
echo "   ↓"
echo "Response JSON"
echo ""
echo "================================"
